name: learn-github-actions
on:
  milestone:
    types: [created,opened,edited,deleted]
# env:
#   SLACK_BOT_TOKEN: ${{ secrets.BASE_SLACK_NOTIFICATION_GITHUB_DISCUSSIONS_TOKEN }}
#   slackChannelId: C02AY7BRG1E
jobs:
  check-bats-version:
    runs-on: ubuntu-latest
    steps:
      - name: Send GitHub MileStone Notification
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '14'
      - run: npm install -g bats
      # - run: echo ${{name}}
      # - run: echo ${{on.milestone.types}}
      - run: echo ${{github.event.milestone.title}}
      - run: echo ${{github.event.milestone.due_on}}
      - run: echo ${{github.event.milestone.description}}



# [x] マイルストーンのステータスを変更した時
# [x] 対象者,日付,descriptionの内容を取得する
# slackに通知する
