name: learn-github-actions
on:
  milestone:
    types: [created,opened,edited,deleted]
# env:
#   SLACK_BOT_TOKEN: ${{ secrets.BASE_SLACK_NOTIFICATION_GITHUB_DISCUSSIONS_TOKEN }}
#   slackChannelId: C02AY7BRG1E
jobs:
  check-bats-version:
    runs-on: ubuntu-latest
    steps:
      - name: Send GitHub Discussion Notification to Slack
        uses: slackapi/slack-github-action@v1.21.0
        with:
          channel-id: ${{ env.slackChannelId }}
          payload: |
            {
              "attachments": [
                {
                  "mrkdwn_in": ["pretext", "text"],
                  "title": "${{github.event.milestone.title}}/${{github.event.milestone.due_on}}",
                  "title_link": "${{github.event.milestone.html_url}}",
                  "text": ${{ toJSON(github.event.milestone.description) }}
                }
              ]
            }
      




# [x] マイルストーンのステータスを変更した時
# [x] 名前,タイトル,日付,description,リンク先の内容を取得する
# - run: echo ${{github.event.milestone.creator.html_url}}:.html_url
# - run: echo ${{github.event.milestone.creator.login}}:login
# - run: echo ${{github.event.milestone.title}}
# - run: echo ${{github.event.milestone.due_on}}
# - run: echo ${{github.event.milestone.description}}
# slackに通知する


